title: Standard

status:
  draft: Entwurf
  unlisted: Veröffentlicht aber nicht im Menü
  listed: Im Menü

options:
  changeTemplate:
    - default-empty

tabs:
  content:
    label: Inhalt
    icon: page
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              builder:
                label: Inhaltsblöcke
                type: blocks
                fieldsets:
                  - bodytext
                  - bodyimage
                  - podcastEmbed
                  - download
      - width: 1/3
        sections:
          pages:
            label: Seiten
            icon: page
            type: pages
            image: icon
            create:
              - default
  other: tabs/other
