title: Standard

status:
  draft: Entwurf
  listed: Veröffentlicht

tabs:
  content:
    label: Inhalt
    icon: page
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              builder:
                label: Inhaltsblöcke
                type: blocks
                fieldsets:
                  - bodytext
                  bodyimage:
                    label: Bild
                    fields:
                      picture: bodyimage
                      size:
                        label: Größe
                        type: select
                        options:
                          default: Standard
                          small: Klein (z.b. Logos)
                          original: kein Zuschnitt
                  download:
                    label: Download-Feld
                    fields:
                      text:
                        label: Text
                        type: textarea
                        buttons: false
                      file:
                        label: Datei
                        type: select
                        options: documents
                        required: true
      - width: 1/3
        sections:
          pages:
            label: Seiten
            icon: page
            type: pages
            image: icon
            create:
              - default
  other: tabs/other
            