title: Projekt
icon: community-line

status:
  draft: Entwurf
  listed: Veröffentlicht

tabs:
  content:
    label: Inhalt
    icon: page
    columns:
      - width: 2/3
        sections:
          content:
            type: fields
            fields:
              builder:
                label: Inhaltsblöcke
                type: blocks
                fieldsets:
                  - bodytext
                  - bodyimage
                  - podcastEmbed
                  - download
      - width: 1/3
        sections:
          meta:
            type: fields
            fields:
              year:
                label: Jahr
                type: text
              teaser_picture:
                extends: fields/bodyimage
                label: Teaser-Bild
                help: "Mindestbreite: 1000px"
          images:
            label: Bilder
            icon: image
            type: files
            uploads: image
            query: page.images

  other: tabs/other
